/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

let _deepseek_ai_dsh_api_comfyui_controller_comfyImages_cancel_parameter_0$schema$value
const _deepseek_ai_dsh_api_comfyui_controller_comfyImages_cancel_parameter_0$schema = () => (_deepseek_ai_dsh_api_comfyui_controller_comfyImages_cancel_parameter_0$schema$value ??= z.object({
  'promptId': z.string().readonly(),
}))
let _deepseek_ai_dsh_api_comfyui_controller_comfyImages_cancel_result$schema$value
const _deepseek_ai_dsh_api_comfyui_controller_comfyImages_cancel_result$schema = () => (_deepseek_ai_dsh_api_comfyui_controller_comfyImages_cancel_result$schema$value ??= z.void())
let _deepseek_ai_dsh_api_comfyui_controller_comfyImages_deleteGeneration_parameter_0$schema$value
const _deepseek_ai_dsh_api_comfyui_controller_comfyImages_deleteGeneration_parameter_0$schema = () => (_deepseek_ai_dsh_api_comfyui_controller_comfyImages_deleteGeneration_parameter_0$schema$value ??= z.object({
  'promptId': z.string().readonly(),
}))
let _deepseek_ai_dsh_api_comfyui_controller_comfyImages_deleteGeneration_result$schema$value
const _deepseek_ai_dsh_api_comfyui_controller_comfyImages_deleteGeneration_result$schema = () => (_deepseek_ai_dsh_api_comfyui_controller_comfyImages_deleteGeneration_result$schema$value ??= z.void())
let _deepseek_ai_dsh_api_comfyui_controller_comfyImages_generate_parameter_0$schema$value
const _deepseek_ai_dsh_api_comfyui_controller_comfyImages_generate_parameter_0$schema = () => (_deepseek_ai_dsh_api_comfyui_controller_comfyImages_generate_parameter_0$schema$value ??= z.object({
  'prompt': z.string().readonly(),
  'negativePrompt': z.string().readonly(),
  'model': z.union([z.literal(null), z.string()]).readonly(),
  'workflow': z.union([z.literal(null), z.string()]).readonly(),
  'width': z.number().readonly(),
  'height': z.number().readonly(),
  'steps': z.number().readonly(),
  'cfg': z.number().readonly(),
  'seed': z.union([z.literal(null), z.number()]).readonly(),
  'batchSize': z.number().readonly(),
}))
let _deepseek_ai_dsh_api_comfyui_controller_comfyImages_generate_result$schema$value
const _deepseek_ai_dsh_api_comfyui_controller_comfyImages_generate_result$schema = () => (_deepseek_ai_dsh_api_comfyui_controller_comfyImages_generate_result$schema$value ??= z.object({
  'promptId': z.string().readonly(),
  'seed': z.number().readonly(),
}))
let _deepseek_ai_dsh_api_comfyui_controller_comfyImages_history_parameter_0$schema$value
const _deepseek_ai_dsh_api_comfyui_controller_comfyImages_history_parameter_0$schema = () => (_deepseek_ai_dsh_api_comfyui_controller_comfyImages_history_parameter_0$schema$value ??= z.object({
  'limit': z.number().readonly(),
}))
let _deepseek_ai_dsh_api_comfyui_controller_comfyImages_history_result$schema$value
const _deepseek_ai_dsh_api_comfyui_controller_comfyImages_history_result$schema = () => (_deepseek_ai_dsh_api_comfyui_controller_comfyImages_history_result$schema$value ??= z.array(z.object({
  'promptId': z.string().readonly(),
  'state': z.union([z.literal("complete"), z.literal("error")]).readonly(),
  'workflow': z.union([z.literal(null), z.string()]).readonly(),
  'workflowLabel': z.string().readonly(),
  'prompt': z.string().readonly(),
  'negativePrompt': z.string().readonly(),
  'model': z.string().readonly(),
  'modelLabel': z.string().readonly(),
  'width': z.number().readonly(),
  'height': z.number().readonly(),
  'steps': z.number().readonly(),
  'cfg': z.number().readonly(),
  'seed': z.number().readonly(),
  'images': z.array(z.object({
  'filename': z.string().readonly(),
  'subfolder': z.string().readonly(),
  'type': z.string().readonly(),
})).readonly(),
})))
let _deepseek_ai_dsh_api_comfyui_controller_comfyImages_image_parameter_0$schema$value
const _deepseek_ai_dsh_api_comfyui_controller_comfyImages_image_parameter_0$schema = () => (_deepseek_ai_dsh_api_comfyui_controller_comfyImages_image_parameter_0$schema$value ??= z.object({
  'filename': z.string().readonly(),
  'subfolder': z.string().readonly(),
  'type': z.string().readonly(),
}))
let _deepseek_ai_dsh_api_comfyui_controller_comfyImages_image_result$schema$value
const _deepseek_ai_dsh_api_comfyui_controller_comfyImages_image_result$schema = () => (_deepseek_ai_dsh_api_comfyui_controller_comfyImages_image_result$schema$value ??= z.object({
  'contentType': z.string().readonly(),
  'base64': z.string().readonly(),
}))
let _deepseek_ai_dsh_api_comfyui_controller_comfyImages_status_result$schema$value
const _deepseek_ai_dsh_api_comfyui_controller_comfyImages_status_result$schema = () => (_deepseek_ai_dsh_api_comfyui_controller_comfyImages_status_result$schema$value ??= z.object({
  'reachable': z.boolean().readonly(),
  'baseUrl': z.string().readonly(),
  'models': z.array(z.object({
  'id': z.string().readonly(),
  'label': z.string().readonly(),
  'kind': z.union([z.literal("checkpoint"), z.literal("z-image-turbo")]).readonly(),
  'recommendedSteps': z.number().readonly(),
  'recommendedCfg': z.number().readonly(),
})).readonly(),
  'workflows': z.array(z.object({
  'id': z.string().readonly(),
  'label': z.string().readonly(),
  'source': z.union([z.literal("built-in"), z.literal("saved")]).readonly(),
  'available': z.boolean().readonly(),
  'unavailableReason': z.union([z.literal(null), z.string()]).readonly(),
  'recommendedSteps': z.number().readonly(),
  'recommendedCfg': z.number().readonly(),
  'supportsNegativePrompt': z.boolean().readonly(),
})).readonly(),
  'error': z.union([z.literal(null), z.string()]).readonly(),
}))

export const TYPERT = {
  package: '@deepseek-ai/dsh-api-comfyui-controller',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: '@deepseek-ai/dsh-api-comfyui-controller#comfyImages/cancel',
      service: 'comfyImagesController',
      namespace: 'comfyImages',
      method: 'cancel',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-api-comfyui-controller/types#ComfyCancelRequest',
            create: _deepseek_ai_dsh_api_comfyui_controller_comfyImages_cancel_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-api-comfyui-controller#comfyImages/cancel:result',
        create: _deepseek_ai_dsh_api_comfyui_controller_comfyImages_cancel_result$schema,
      },
      sourceLocation: {"file":"packages/api/comfyui-controller/src/index.ts","line":675,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-api-comfyui-controller#comfyImages/deleteGeneration',
      service: 'comfyImagesController',
      namespace: 'comfyImages',
      method: 'deleteGeneration',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-api-comfyui-controller/types#ComfyDeleteRequest',
            create: _deepseek_ai_dsh_api_comfyui_controller_comfyImages_deleteGeneration_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-api-comfyui-controller#comfyImages/deleteGeneration:result',
        create: _deepseek_ai_dsh_api_comfyui_controller_comfyImages_deleteGeneration_result$schema,
      },
      sourceLocation: {"file":"packages/api/comfyui-controller/src/index.ts","line":664,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-api-comfyui-controller#comfyImages/generate',
      service: 'comfyImagesController',
      namespace: 'comfyImages',
      method: 'generate',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-api-comfyui-controller/types#ComfyGenerateRequest',
            create: _deepseek_ai_dsh_api_comfyui_controller_comfyImages_generate_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-api-comfyui-controller/types#ComfyGenerateReceipt',
        create: _deepseek_ai_dsh_api_comfyui_controller_comfyImages_generate_result$schema,
      },
      sourceLocation: {"file":"packages/api/comfyui-controller/src/index.ts","line":592,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-api-comfyui-controller#comfyImages/history',
      service: 'comfyImagesController',
      namespace: 'comfyImages',
      method: 'history',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-api-comfyui-controller/types#ComfyHistoryRequest',
            create: _deepseek_ai_dsh_api_comfyui_controller_comfyImages_history_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-api-comfyui-controller#comfyImages/history:result',
        create: _deepseek_ai_dsh_api_comfyui_controller_comfyImages_history_result$schema,
      },
      sourceLocation: {"file":"packages/api/comfyui-controller/src/index.ts","line":640,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-api-comfyui-controller#comfyImages/image',
      service: 'comfyImagesController',
      namespace: 'comfyImages',
      method: 'image',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-api-comfyui-controller/types#ComfyImageRequest',
            create: _deepseek_ai_dsh_api_comfyui_controller_comfyImages_image_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-api-comfyui-controller/types#ComfyImageData',
        create: _deepseek_ai_dsh_api_comfyui_controller_comfyImages_image_result$schema,
      },
      sourceLocation: {"file":"packages/api/comfyui-controller/src/index.ts","line":652,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-api-comfyui-controller#comfyImages/status',
      service: 'comfyImagesController',
      namespace: 'comfyImages',
      method: 'status',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-api-comfyui-controller/types#ComfyImagesStatus',
        create: _deepseek_ai_dsh_api_comfyui_controller_comfyImages_status_result$schema,
      },
      sourceLocation: {"file":"packages/api/comfyui-controller/src/index.ts","line":573,"column":9},
    },
  ],
  model: {
    "services": [
      {
        "description": "Remote controller used by the Images Cordis UI plugin.",
        "summary": "Remote controller used by the Images Cordis UI plugin.",
        "tags": [],
        "jsDoc": "/** Remote controller used by the Images Cordis UI plugin. */",
        "key": "comfyImagesController",
        "exportName": "ComfyImagesController",
        "members": [
          {
            "kind": "method",
            "name": "status",
            "signature": "@Remote async status(signal: AbortSignal): Promise<ComfyImagesStatus>",
            "summary": "Probe ComfyUI and list locally installed model configurations Arya can run.",
            "jsDoc": "/** Probe ComfyUI and list locally installed model configurations Arya can run. */"
          },
          {
            "kind": "method",
            "name": "generate",
            "signature": "@Remote async generate(request: ComfyGenerateRequest, signal: AbortSignal): Promise<ComfyGenerateReceipt>",
            "summary": "Queue one standard-node text-to-image workflow.",
            "jsDoc": "/** Queue one standard-node text-to-image workflow. */"
          },
          {
            "kind": "method",
            "name": "history",
            "signature": "@Remote async history(request: ComfyHistoryRequest, signal: AbortSignal): Promise<readonly ComfyGeneration[]>",
            "summary": "Read completed and failed generations from ComfyUI history.",
            "jsDoc": "/** Read completed and failed generations from ComfyUI history. */"
          },
          {
            "kind": "method",
            "name": "image",
            "signature": "@Remote async image(request: ComfyImageRequest, signal: AbortSignal): Promise<ComfyImageData>",
            "summary": "Read one output image through the Host so browser CORS never reaches ComfyUI.",
            "jsDoc": "/** Read one output image through the Host so browser CORS never reaches ComfyUI. */"
          },
          {
            "kind": "method",
            "name": "deleteGeneration",
            "signature": "@Remote async deleteGeneration(request: ComfyDeleteRequest, signal: AbortSignal): Promise<void>",
            "summary": "Remove one completed generation from ComfyUI history.",
            "jsDoc": "/** Remove one completed generation from ComfyUI history. */"
          },
          {
            "kind": "method",
            "name": "cancel",
            "signature": "@Remote async cancel(request: ComfyCancelRequest, signal: AbortSignal): Promise<void>",
            "summary": "Remove a queued prompt and interrupt the current execution when it is running.",
            "jsDoc": "/** Remove a queued prompt and interrupt the current execution when it is running. */"
          }
        ],
        "types": [
          {
            "name": "ComfyCancelRequest",
            "declaration": "export interface ComfyCancelRequest {\n    readonly promptId: string;\n}"
          },
          {
            "name": "ComfyDeleteRequest",
            "declaration": "export interface ComfyDeleteRequest {\n    readonly promptId: string;\n}"
          },
          {
            "name": "ComfyGenerateReceipt",
            "declaration": "export interface ComfyGenerateReceipt {\n    readonly promptId: string;\n    readonly seed: number;\n}"
          },
          {
            "name": "ComfyGenerateRequest",
            "declaration": "export interface ComfyGenerateRequest {\n    readonly prompt: string;\n    readonly negativePrompt: string;\n    readonly model: string | null;\n    readonly workflow: string | null;\n    readonly width: number;\n    readonly height: number;\n    readonly steps: number;\n    readonly cfg: number;\n    readonly seed: number | null;\n    readonly batchSize: number;\n}"
          },
          {
            "name": "ComfyGeneration",
            "declaration": "export interface ComfyGeneration {\n    readonly promptId: string;\n    readonly state: 'complete' | 'error';\n    readonly workflow: string | null;\n    readonly workflowLabel: string;\n    readonly prompt: string;\n    readonly negativePrompt: string;\n    readonly model: string;\n    readonly modelLabel: string;\n    readonly width: number;\n    readonly height: number;\n    readonly steps: number;\n    readonly cfg: number;\n    readonly seed: number;\n    readonly images: ComfyImageReference[];\n}"
          },
          {
            "name": "ComfyHistoryRequest",
            "declaration": "export interface ComfyHistoryRequest {\n    readonly limit: number;\n}"
          },
          {
            "name": "ComfyImageData",
            "declaration": "export interface ComfyImageData {\n    readonly contentType: string;\n    readonly base64: string;\n}"
          },
          {
            "name": "ComfyImageModel",
            "declaration": "export interface ComfyImageModel {\n    readonly id: string;\n    readonly label: string;\n    readonly kind: 'checkpoint' | 'z-image-turbo';\n    readonly recommendedSteps: number;\n    readonly recommendedCfg: number;\n}"
          },
          {
            "name": "ComfyImageReference",
            "declaration": "export interface ComfyImageReference {\n    readonly filename: string;\n    readonly subfolder: string;\n    readonly type: string;\n}"
          },
          {
            "name": "ComfyImageRequest",
            "declaration": "export interface ComfyImageRequest extends ComfyImageReference {\n}"
          },
          {
            "name": "ComfyImagesStatus",
            "declaration": "export interface ComfyImagesStatus {\n    readonly reachable: boolean;\n    readonly baseUrl: string;\n    readonly models: ComfyImageModel[];\n    readonly workflows: ComfyImageWorkflow[];\n    readonly error: string | null;\n}"
          },
          {
            "name": "ComfyImageWorkflow",
            "declaration": "export interface ComfyImageWorkflow {\n    readonly id: string;\n    readonly label: string;\n    readonly source: 'built-in' | 'saved';\n    readonly available: boolean;\n    readonly unavailableReason: string | null;\n    readonly recommendedSteps: number;\n    readonly recommendedCfg: number;\n    readonly supportsNegativePrompt: boolean;\n}"
          }
        ]
      }
    ],
    "events": [],
    "objects": []
  },
}
